apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kfserving-controller-manager
  namespace: kfserving-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: uhub.service.ucloud.cn/mirrors/kfserving-controller:v0.6.0
        name: manager
